### ISSUE TITLE
Missing Doc Pages

### ISSUE THREAD

**Issue by obastemur** [ms-iot/ntvsiot#108]
```
https://developer.microsoft.com/en-us/windows/iot/docs/StartCoding.htm 
and a whole bunch of other IoT doc pages are PageNotFound :(
```

See https://github.com/Microsoft/ChakraCore/issues/1428

**Comment by munyirik** [comment]
I've commented on the issue in the ChakraCore repo. Did you see a broken link this this repo? if not I'll close this.

**Comment by obastemur** [comment]
@munyirik Thanks
