### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by fmalekpour** [ms-iot/ntvsiot#109]
Using Node.js Tools for UWP Apps 1.5.4, I can't get console.log to work, it does not give any error and app works fine on Windows IoT on Raspberry Pi 3, but no sign of console.log in output window.

**Comment by munyirik** [comment]
Can you check thta you're passing '--debug' to node in the project properties? It's required for console.log to redirect to the output window.
![image](https://cloud.githubusercontent.com/assets/8389594/17779443/80a70e06-651c-11e6-86a8-19bcb683949c.png)

**Comment by fmalekpour** [comment]
That did the trick. Thanks.
