### ISSUE TITLE
console.log doesn't show in the VS Debug/Output Window

### ISSUE THREAD

**Issue by mikehall-ms** [ms-iot/ntvsiot#15]
when writing Node.JS applications it is common practice to use console.log to show certain events (app running, listening, REST/POST call received etc...). The current implementation of NTVSIoT doesn't show console.log output in the VS output window.

**Comment by munyirik** [comment]
Fix will be in the next release.

**Comment by munyirik** [comment]
Fix available in https://github.com/ms-iot/ntvsiot/releases/tag/v1.3
