### ISSUE TITLE
Deployment of Node Express UWP application to x86 fails

### ISSUE THREAD

**Issue by mikehall-ms** [ms-iot/ntvsiot#23]
installing NTVS from \\scratch2\scratch\munyirik\Node.js\BundleInstaller - generating a default Node Express UWP application, setting build to x86, configuring project properties for x86 device IP address, building and deploying fails with error message DEP0700: Registration of the app failed. Windows cannot install package Express4UWPApp6 because the package requires Architecture ARM, but this computer has architecture x86 (0x80073d10).

the project bin\appmanifest.xml has line 10 <Identity Name="Express4UWPApp6" Publisher="CN-mikehall" version="1.0.0.0" ProcessorArchitecture="arm" />

**Comment by munyirik** [comment]
Fix will be in the next release

**Comment by munyirik** [comment]
As a workaround for now, rebuilding (Build Menu -> Rebuild Solution) is required if architecture is changed.
