### ISSUE TITLE
Remote debugging fails with "Unable to open script document"

### ISSUE THREAD

**Issue by arturl** [ms-iot/ntvsiot#33]
Set a breakpoint anywhere in the server.js, get this pop-up:

> Unable to open script document. The debugger is not properly installed.  Run setup to install or repair the debugger.

**Comment by munyirik** [comment]
@arturl Did you get this issue resolved? If I recall even debugging WinJS was broken.

**Comment by arturl** [comment]
Yes, thanks. Issue was resolve by VS reinstall.

Artur

**Comment by munyirik** [comment]
@arturl thanks. please close if it's no longer an issue.
