### ISSUE TITLE
"Git for Windows" is confusing

### ISSUE THREAD

**Issue by SteveALee** [ms-iot/ntvsiot#63]
In the [1.3 release](https://github.com/ms-iot/ntvsiot/releases/tag/v1.3) notes you have a link called **Git for Windows**. I suggest you  rename it as **Windows port of Git** as [Git for Windows](https://git-for-windows.github.io/) is a different tool which includes the git port and the MSYS Bash shell. Or perhaps change the link :)

**Comment by SteveALee** [comment]
My bad - it is exactly the same installer executable. Arguably the 2nd link is more informative though

**Comment by munyirik** [comment]
Hi @SteveALee Thanks for the suggestion. I'll use the 2nd link for the next release.
