### ISSUE TITLE
Thank you guys for your work!!

### ISSUE THREAD

**Issue by michaelderemer** [ms-iot/ntvsiot#90]
1.5.3 was the first version that installed and worked easily and without any problems. Thank you guys for your hard work. Thanks for cleaning it up. Its just gonna keep getting better! So crazy that i'm coding windows apps for an ARM machine. Tell Bill G i said thanks :) So exciting. Good stuff.

**Comment by munyirik** [comment]
Great to hear! And thanks for the kind works. Please let us know if you run into any more issues, have questions, suggestions, etc.
