### ISSUE TITLE
the procedure entry point JsInstanceOf could not be located in the dynamic link library

### ISSUE THREAD

**Issue by stanleyoho** [ms-iot/ntvsiot#94]
hello i can't excute Node.js (chakra) command prompt.

when i open it , will show this error message "the procedure entry point JsInstanceOf could not be located in the dynamic link library C:\Program File\NodejsUwp\Console\node.exe"

anyone know this ?

**Comment by munyirik** [comment]
Hi @stanleyoho,
What version of Node.js (chakra) do you have? You can check the 'Version' column in 'Control Panel\Programs\Programs and Features'
Also can you tell me what version of Windows you have? (you can copy/paste the output from the command `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`).

**Comment by munyirik** [comment]
@stanleyoho I'm closing this for now. Please re-open if this is still an problem for you.
