### ISSUE TITLE
Please pack NTVS.1.2.RC.VS.2015 into the installer

### ISSUE THREAD

**Issue by EdiWang** [ms-iot/ntvsiot#99]
The latest NTVS is 1.2 RC now. Please update NTVSIOT installer to include that package.

**Comment by munyirik** [comment]
Hello @EdiWang I'm planning on releasing it next week.

**Comment by EdiWang** [comment]
@munyirik Thanks!

**Comment by munyirik** [comment]
Here it is - https://github.com/ms-iot/ntvsiot/releases/tag/v1.5.4.
